/*
 * Alarming
 *
 * Alarming API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	alarming "github.com/sbnarra/alarming-api/pkg/generated/server"
)

func main() {
	log.Printf("Server started")

	DefaultApiService := alarming.NewDefaultApiService()
	DefaultApiController := alarming.NewDefaultApiController(DefaultApiService)

	router := alarming.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
